# Workflow to build Tessalatrix cross-platform, and pull together release
# packages automagically.
#
# For now, we only build a Linux/SDL target, but via a matrix so that in 
# future we can support multiple targets

name: CMake

# Build whenever we push; package on release
on: 
  push:
  release:
    types: [published]


jobs:
  build:
    name: ${{matrix.name}}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            name: Linux
            release-suffix: linux
            cmake-args: 
            apt-packages: libsdl2-dev libsdl2-image-dev

    runs-on: ${{matrix.os}}

    env:
      BUILD_TYPE: Release

    steps:

    # Check out our own repo.
    - name: Checkout Tessalatrix
      uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      if: runner.os == 'Linux'
      run: sudo apt update && sudo apt install ${{matrix.apt-packages}}

    # Configure cmake
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    # Run the build
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # On releases, get cmake to build the packages
    - name: Package
      if github.event_name == 'release'
      run: cd ${{github.workspace}}/build && cpack
      uses: softprops/action-gh-release@v1
        with:
          files: *.zip *.tar.gz
